game:

  respawns:
    # Number of lives each player starts with. A player's life is removed if they are eliminated.
    default-lives: 1

    # Time (in seconds) a player must wait before respawning. This only applies if they still have remaining lives.
    respawn-seconds: 5

  misc:
    # Should players be allowed to join an ongoing countdown after everyone has already been placed into their starting cages?
    allow-join-during-start: true

    # Default gamemode used for active players (spectators excluded).
    default-gamemode: adventure

  command-actions:
    # Execute console commands upon common game events.
    # Leaving a list empty will execute no commands.
    # Commands should NOT begin with "/"

    on-lobby:
      # Available placeholders: {player}, {game}
      # NOT A LOOP! Runs for individual players in the lobby if they newly join.
      -

    on-prep:
      # Available placeholders: {game}
      # NOT A LOOP! Runs ONLY one time while the arena is prepped and players are spawned.
      -

    on-start:
      # Available placeholders: {player}, {game}
      # Runs once for every player after game completely starts. Runs again for individual players if they newly join.
      -

    on-death:
      # Available placeholders: {player}, {game}
      # Runs once for a single players' death
      -

    on-kill:
      # Available placeholders: {attacker}, {player}

      # Runs once for a players' death and involves the attacker.
      # [!] Beware of duplicate commands. The command actions in on-death will also run during a kill.
      -

    on-win:
      # Available placeholders {player}, {game}

      # Runs once for every player on the winning team.
      -

    on-lose:
      # Available placeholders {player}, {game}

      # Runs once for every player on any losing team.
      -


  teams:
    # Team display prefixes.
    #
    # The plugin assigns teams using this list in order. Team color is automatically derived from the color codes used in each prefix.
    #
    # If this list is shorter than the number of required teams,
    # remaining teams will automatically be named: ["&aTeam 1", "&aTeam 2", "&aTeam 3"]
    names:
      ["&dTeam 1 ", "&dTeam 2 ", "&dTeam 3 ", "&dTeam 4 "]

    # Short team names used where space is limited. Should contain the same number of entries as "names".
    short-names:
      ["T1", "T2", "T3", "T4"]

  timers:
    # Seconds players wait in the lobby before being moved into the arena.
    lobby-countdown: 10

    # Seconds players wait inside their starting cages before the game officially begins.
    game-countdown: 10

    # Seconds after the game starts before global PvP invulnerability is removed.
    invul-countdown: 15

    # Seconds after the game starts before all refillable chests are refreshed.
    chest-refill: 150

    # Seconds after the game starts before SHOWDOWN (world border event & name highlighting) begins.
    showdown: 300

    # Maximum game duration in seconds from the start until the end.
    game-end: 360


scoreboards:
  # Enables or disables scoreboards entirely
  enabled: true

  # Scoreboards do not use the CXYZ message parser, but placeholders values are still supported.
  # Minecraft scoreboards cannot contain duplicate values. You can use color codes (i.e.: "&a", "&6") for unique blank separators.

  lobby:
    - "&6&lSpeed&a&lSG" # The first entry of this list will become the scoreboard title
    - "&7{date-short}"
    - "&7{time-short}"
    - "&0"
    - "&eYou are on {player-team-prefix}"
    - "&1"
    - "&eRank: {player-rank-prefix-display}"
    - "&2"
    - "&eKills: &f{player-stat-sg-lifetime-kills} &7(#{player-stat-sg-lifetime-kills-ranking})"
    - "&eWins: &f{player-stat-sg-lifetime-wins} &7(#{player-stat-sg-lifetime-wins-ranking})"
    - "&3"
    - "&e{game-next-event}: &f{game-next-event-time}"
    - "&4"
    - "&b&l/discord"
    - "&6cerrot.xyz"

  game:
    - "&6&lSpeed&a&lSG"
    - "&7{date-short}"
    - "&7{time-short}"
    - "&1"
    - "&eYou are on {player-team-prefix}"
    - "&2"
    - "&eKills: &f{player-temp-stat-kills}"
    - "&eLives: &f{player-lives}"
    - "&eRemaining: &f{game-alive-players-size}/{game-original-players-size}"
    - "&3"
    - "&e{game-next-event}: &f{game-next-event-time}"
    - "&4"
    - "&eMap: &f{game-map}"
    - "&5"
    - "&b&l/discord"
    - "&6cerrot.xyz"