name: ssg
version: '0.0'
main: com.carrotguy69.ssg.SpeedSG
api-version: '1.21'

depend:
  - cxyz

softdepend:
  - PlaceholderAPI



commands:
  test:
    description: Test this command
    usage: /channel <args>
    permission: "ssg.test"
    aliases: [ chat, chatchannel ]

permissions:
  ssg.test:
    default: true