# schema is work in progress

teams:
  # The plugin will iterate through this list to find its team prefixes.
  # In solos mode (team maxCapacity=1), the prefixes will just be the player names.
  # If this list is left empty or too small to cover all teams, the default behavior is: ["&aTeam 1", "&aTeam 2", "&Team 3", ...]
  # Team color is derived from the prefix text.
  names:
    ["&aTeam 1", "&bTeam 2", "&cTeam 3", "&dTeam 4"]

timers:
  # Amount of seconds to count down from, before moving the lobby to the game arena
  lobby-countdown: 10

  # Amount of seconds to count down from, before starting the game (when players are already in the arena)
  game-countdown: 10

  # Amount of seconds to count down from the game start, before removing global invulnerability.
  invulnerability-countdown: 15

  # Amount of seconds to count down from the game start, before refilling chests.
  chest-refill: 150

  # Amount of seconds to count down from the game start, until the SHOWDOWN event (players are highlighted)
  showdown: 300

  # Amount of seconds to count down from the game start, before the game forcibly declares a winner and ends.
  game-end: 360