game:

  respawns:
    default-lives: 1
    respawn-seconds: 5

  misc:
    # Should the game allow players to participate when players are already in their cages and the timer is counting?
    allow-join-during-start: true
    default-gamemode: adventure

  command-actions:
    # Execute console commands upon common game events

    on-death:
      # placeholders: {player}


    on-kill:
      # placeholders: {attacker}, {player}
      -

    on-win:
      # placeholder {player}
      -

  teams:
    # The plugin will iterate through this list to find its team prefixes.
    # If this list is left empty or too small to cover all teams, the default behavior is: ["&aTeam 1", "&aTeam 2", "&Team 3", ...]
    # Team color is derived from the prefix text.
    names:
      ["&dTeam 1 ", "&dTeam 2 ", "&dTeam 3 ", "&dTeam 4 "]

    short-names:
      ["T1", "T2", "T3", "T4"]

  timers:
    # Amount of seconds to count down from, before moving the lobby to the game arena
    lobby-countdown: 10

    # Amount of seconds to count down from, before starting the game (when players are already in the arena)
    game-countdown: 10

    # Amount of seconds to count down from the game start, before removing global invulnerability
    invul-countdown: 15

    # Amount of seconds to count down from the game start, before refilling chests
    chest-refill: 150

    # Amount of seconds to count down from the game start, until the SHOWDOWN event (players are highlighted)
    showdown: 300

    # Amount of seconds to count down from the game start, before the game forcibly declares a winner and ends
    game-end: 360


scoreboards:
  # Scoreboards do not use the CXYZ message parser, but you can still use placeholders

  lobby:
    - "&6&lSpeed&a&lSG"
    - "&7{date-short}"
    - "&7{time-short}"
    - "&0"
    - "&eRank: {player-rank-prefix-display}"
    - "&1"
    - "&eKills: &f{player-stat-sg-lifetime-kills} &7(#{player-stat-sg-lifetime-kills-ranking})"
    - "&eWins: &f{player-stat-sg-lifetime-wins} &7(#{player-stat-sg-lifetime-wins-ranking})"
    - "&2"
    - "&3"
    - "&b&l/discord"
    - "&6cerrot.xyz"

  game:
    - "&6&lSpeed&a&lSG"
    - "&7{date-short}"
    - "&7{time-short}"
    - "&1"
    - "&eYou are on {player-team-prefix}"
    - "&2"
    - "&eKills: &f{player-temp-stat-kills}"
    - "&eLives: &f{player-lives}"
    - "&eRemaining: &f{game-alive-players-size}/{game-original-players-size}"
    - "&3"
    - "&a{game-next-event}: &f{game-next-event-time}"
    - "&4"
    - "&eMap: &f{game-map}"
    - "&5"
    - "&b&l/discord"
    - "&6cerrot.xyz"