name: ssg
version: '0.0'
main: com.carrotguy69.ssg.SpeedSG
api-version: '1.21'

depend:
  - cxyz
  - WorldEdit

softdepend:
  - PlaceholderAPI

commands:
  ssg:
    description: Manage a SpeedSG game instance
    usage: /ssg <create | delete | freeze | info| join | leave | list | ready | respawn | setlives | setting> [...]
    permission: "ssg"


permissions:
  ssg.test:
    default: op

  ssg.print:
    default: op

  ssg:
    default: true
  ssg.create:
    default: op
  ssg.delete:
    default: op
  ssg.join:
    default: true
  ssg.leave:
    default: true
  ssg.list:
    default: true
  ssg.info:
    default: true
  ssg.setting:
    default: op
  ssg.freeze:
    default: op
  ssg.respawn:
    default: op
  ssg.setlives:
    default: op
  ssg.ready:
    default: true

  ssg.team:
    default: true
  ssg.team.join:
    default: true
  ssg.team.leave:
    default: true
  ssg.team.list:
    default: true